Fixed translation of login link.
i18ndude gave an AttributeError: 'NoneType' object has no attribute 'encode'.
This is because we were using `i18n:attributes` on an attribute `value`, where we should have simply used `i18n:translate` for the content of the tag.